<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Juan Camilo Gutiérrez Martínez CC 1033486192">
<meta name="author" content="Maria Fernanda Calle Agudelo CC 1033428469">
<meta name="author" content="Jaider Castañeda Villa CC 1001015442">
<meta name="dcterms.date" content="2025-07-01">

<title>Mapas del Departamento del Cauca</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="proyenc_files/libs/clipboard/clipboard.min.js"></script>
<script src="proyenc_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="proyenc_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="proyenc_files/libs/quarto-html/popper.min.js"></script>
<script src="proyenc_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proyenc_files/libs/quarto-html/anchor.min.js"></script>
<link href="proyenc_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proyenc_files/libs/quarto-html/quarto-syntax-highlighting-7b4406b7675125bc2ba204020e191172.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proyenc_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proyenc_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proyenc_files/libs/bootstrap/bootstrap-fa5a175d901523c42d64f4c229f2b4f6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos">Objetivos</a></li>
  <li><a href="#metodología-y-procedimientos" id="toc-metodología-y-procedimientos" class="nav-link" data-scroll-target="#metodología-y-procedimientos">Metodología y Procedimientos</a></li>
  <li><a href="#mapas" id="toc-mapas" class="nav-link" data-scroll-target="#mapas">Mapas</a>
  <ul class="collapse">
  <li><a href="#mapa-del-departamento" id="toc-mapa-del-departamento" class="nav-link" data-scroll-target="#mapa-del-departamento">Mapa del departamento</a></li>
  <li><a href="#índice-de-necesidades-básicas-insatisfechas-nbi" id="toc-índice-de-necesidades-básicas-insatisfechas-nbi" class="nav-link" data-scroll-target="#índice-de-necesidades-básicas-insatisfechas-nbi">Índice de Necesidades Básicas Insatisfechas (NBI)</a></li>
  <li><a href="#índice-de-desempeño-fiscal" id="toc-índice-de-desempeño-fiscal" class="nav-link" data-scroll-target="#índice-de-desempeño-fiscal">Índice de desempeño fiscal</a></li>
  <li><a href="#distancia-a-la-capital" id="toc-distancia-a-la-capital" class="nav-link" data-scroll-target="#distancia-a-la-capital">Distancia a la capital</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  <li><a href="#recomendaciones" id="toc-recomendaciones" class="nav-link" data-scroll-target="#recomendaciones">Recomendaciones</a></li>
  <li><a href="#cibergrafía" id="toc-cibergrafía" class="nav-link" data-scroll-target="#cibergrafía">Cibergrafía</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mapas del Departamento del Cauca</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Juan Camilo Gutiérrez Martínez CC 1033486192 </p>
             <p>Maria Fernanda Calle Agudelo CC 1033428469 </p>
             <p>Jaider Castañeda Villa CC 1001015442 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>El departamento del Cauca es una región de Colombia ubicada en el suroccidente del país, reconocida por su diversidad geográfica, cultural y étnica. Sin embargo, también enfrenta marcadas desigualdades sociales, económicas y de infraestructura entre sus municipios. Este informe presenta un análisis visual de tres variables clave: la distribución de la pobreza, el índice de desempeño fiscal y la distancia por carretera a su capital, Popayán. A través de mapas temáticos, se busca evidenciar estas diferencias territoriales y aportar elementos para una mejor comprensión del contexto regional.</p>
</section>
<section id="objetivos" class="level1">
<h1>Objetivos</h1>
<ul>
<li><p><strong>Identificación de brechas territoriales:</strong> Detectar diferencias en las condiciones de vida entre municipios del Cauca según el NBI y su ubicación respecto a la capital.</p></li>
<li><p><strong>Análisis de patrones espaciales de pobreza:</strong> Explorar la posible relación entre la lejanía a Popayán y altos niveles de pobreza.</p></li>
<li><p><strong>Evaluación del acceso equitativo a servicios:</strong> Analizar desigualdades en el acceso a salud, educación e infraestructura según la distancia.</p></li>
<li><p><strong>Visualización de desigualdad mediante mapas:</strong> Representar gráficamente las condiciones socioeconómicas y geográficas del departamento.</p></li>
</ul>
</section>
<section id="metodología-y-procedimientos" class="level1">
<h1>Metodología y Procedimientos</h1>
</section>
<section id="mapas" class="level1">
<h1>Mapas</h1>
<section id="mapa-del-departamento" class="level2">
<h2 class="anchored" data-anchor-id="mapa-del-departamento">Mapa del departamento</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyenc_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En total, el departamento del Cauca está conformado por <strong>42 municipios</strong>, cada uno representado en un color distinto en el mapa.</p>
</section>
<section id="índice-de-necesidades-básicas-insatisfechas-nbi" class="level2">
<h2 class="anchored" data-anchor-id="índice-de-necesidades-básicas-insatisfechas-nbi">Índice de Necesidades Básicas Insatisfechas (NBI)</h2>
<p>El mapa muestra el Índice de Necesidades Básicas Insatisfechas (NBI) en los municipios del departamento del Cauca, reflejando los niveles de pobreza estructural en la región. A través de una escala de colores, se evidencia una fuerte desigualdad territorial: mientras algunos municipios tienen un NBI inferior al 20% (color verde), otros superan el 60% (color rojo), indicando condiciones críticas de pobreza.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyenc_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Las zonas más afectadas se ubican principalmente en el noroccidente del departamento, donde una alta proporción de la población carece de acceso adecuado a servicios básicos, vivienda y educación. En contraste, los municipios del centro y oriente muestran mejores condiciones de vida y mayor cobertura de necesidades básicas.</p>
<p>Este contraste territorial destaca la urgencia de intervenir en los municipios más vulnerables mediante políticas públicas focalizadas. El NBI es una herramienta clave para identificar brechas sociales y orientar la inversión hacia las zonas con mayores carencias.</p>
<p>Las zonas más afectadas se ubican principalmente en el noroccidente del departamento, donde una alta proporción de la población carece de acceso adecuado a servicios básicos, vivienda y educación. En contraste, los municipios del centro y oriente muestran mejores condiciones de vida y mayor cobertura de necesidades básicas.</p>
<p>Este contraste territorial destaca la urgencia de intervenir en los municipios más vulnerables mediante políticas públicas focalizadas. El NBI es una herramienta clave para identificar brechas sociales y orientar la inversión hacia las zonas con mayores carencias.</p>
</section>
<section id="índice-de-desempeño-fiscal" class="level2">
<h2 class="anchored" data-anchor-id="índice-de-desempeño-fiscal">Índice de desempeño fiscal</h2>
<p>El Índice de Desempeño Fiscal (IDF) de un municipio es una herramienta que mide la gestión financiera de una entidad territorial (municipio o departamento) en Colombia, evaluando su capacidad para generar ingresos propios, manejar sus deudas, invertir eficientemente y cumplir con las normativas fiscales. En esencia, refleja qué tan bien un municipio administra sus recursos económicos.</p>
<p>Para el ejercicio, nos vamos a enfocar en los municipios del departamento del Cauca, los datos se obtuvieron de la página web del Departamento Nacional de Planeación de Colombia, <a href="https://www.dnp.gov.co/LaEntidad_/subdireccion-general-descentralizacion-desarrollo-territorial/direccion-descentralizacion-fortalecimiento-fiscal/Paginas/informacion-fiscal-y-financiera.aspx" class="uri">https://www.dnp.gov.co/LaEntidad_/subdireccion-general-descentralizacion-desarrollo-territorial/direccion-descentralizacion-fortalecimiento-fiscal/Paginas/informacion-fiscal-y-financiera.aspx</a> actualizado al año 2023.</p>
<p>El mapa muestra la clasificación de cada municipio del Cauca en base a su índice de desempeño fiscal. En la documentación oficial la clasificación está definida así:</p>
<ul>
<li><ol type="1">
<li>Deterioro (&lt;40)</li>
</ol></li>
<li><ol start="2" type="1">
<li>Riesgo (&gt;=40 y &lt;60)</li>
</ol></li>
<li><ol start="3" type="1">
<li>Vulnerable (&gt;=60 y &lt;70)</li>
</ol></li>
<li><ol start="4" type="1">
<li>Solvente (&gt;=70 y &lt;80)</li>
</ol></li>
<li><ol start="5" type="1">
<li>Sostenible (&gt;=80)</li>
</ol></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyenc_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El mapa anterior nos da un vistazo general de las condiciones del departamento del Cauca respecto al IDF, lo primero que se ve es que hay cierta homogeneidad, pues solo hay municipios de dos tipos, en riesgo y vulnerables. Premisa que nos lleva a pensar que el Cauca tiene ciertas limitaciones ecónomicas en sus municipios y no muestran un buen desempeño en los parámetros utilizados para calcular el IDF.</p>
<p>Vamos a hacer un análisis más profundo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  41.65   51.07   54.91   55.39   59.24   69.46 </code></pre>
</div>
</div>
<p>Se puede ver que la media del IDF de todos los municipios es de 54.91, hay un valor máximo de 69.46 y un valor mínimo de 41.65.</p>
<p>Ahora miremos la desviación estándar:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.740795</code></pre>
</div>
</div>
<p>La desviación estándar es baja, lo que reafirma la afirmación de que en cuanto al IDF el departamento del Cauca es muy homogéneo.</p>
<p>Estos son los cincos municipios con más alto IDF:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  Código Municipio      `Nuevo IDF` Rango                     
  &lt;chr&gt;  &lt;chr&gt;                &lt;dbl&gt; &lt;chr&gt;                     
1 19418  LOPEZ DE MICAY        69.5 3. Vulnerable (&gt;=60 y &lt;70)
2 19300  GUACHENE              68.9 3. Vulnerable (&gt;=60 y &lt;70)
3 19809  TIMBIQUI              67.8 3. Vulnerable (&gt;=60 y &lt;70)
4 19290  FLORENCIA             67.7 3. Vulnerable (&gt;=60 y &lt;70)
5 19455  MIRANDA               64.8 3. Vulnerable (&gt;=60 y &lt;70)</code></pre>
</div>
</div>
<p>El municipio Lopez De Micay tiene el índice de desempeño fiscal más alto del departamento.</p>
<p>Estos son los cincos municipios con más bajo IDF:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  Código Municipio        `Nuevo IDF` Rango                 
  &lt;chr&gt;  &lt;chr&gt;                  &lt;dbl&gt; &lt;chr&gt;                 
1 19743  SILVIA                  41.6 2. Riesgo (&gt;=40 y &lt;60)
2 19137  CALDONO                 45.0 2. Riesgo (&gt;=40 y &lt;60)
3 19532  PATIA (EL BORDO)        45.9 2. Riesgo (&gt;=40 y &lt;60)
4 19450  MERCADERES              46.2 2. Riesgo (&gt;=40 y &lt;60)
5 19573  PUERTO TEJADA           47.6 2. Riesgo (&gt;=40 y &lt;60)</code></pre>
</div>
</div>
<p>El municipio de Silvia tiene el IDF más bajo y se encuentra en el límite a convertirse un municipio en deteriorio. (menor a 40).</p>
</section>
<section id="distancia-a-la-capital" class="level2">
<h2 class="anchored" data-anchor-id="distancia-a-la-capital">Distancia a la capital</h2>
<p>Para la elaboración de este mapa se recopilaron las distancias por carretera entre los distintos municipios y la capital (Popayán). Los datos se obtuvieron a través del sitio web <a href="https://colombia.mejoresrutas.com/tabla-de-distancias/co-cauca/" class="uri">https://colombia.mejoresrutas.com/tabla-de-distancias/co-cauca/</a>, el cual permite consultar la distancia vial entre dos municipios de Colombia. Utilizando la lista de municipios del departamento del Cauca previamente recopilada, se construyó una tabla que muestra la distancia por carretera desde cada uno de ellos hacia Popayán. Esta información fue descargada como un archivo en formato <code>.xls</code>, el cual será utilizado como fuente de datos para la elaboración del mapa.</p>
<p>Primero vamos a realizar un análisis de los datos:</p>
<p>El mapa presentado muestra el departamento del Cauca, donde cada municipio está coloreado de acuerdo con su distancia a la ciudad de Popayán. Se utiliza una escala de colores que va del azul (municipios más cercanos) al rojo (municipios más lejanos), permitiendo visualizar de forma clara y comparativa qué tan alejado se encuentra cada municipio respecto a la capital.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyenc_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se observa que los municipios más cercanos, ubicados en el centro del departamento, se representan en tonos azules, mientras que aquellos más alejados, principalmente al sur y en zonas periféricas, presentan colores que van del amarillo al rojo. Esto indica una mayor lejanía respecto a la capital. El patrón de color evidencia que la mayor concentración de municipios se encuentra en un rango intermedio de distancia, mientras que solo algunos municipios, como el ubicado al extremo sur (Piamonte), superan los 300 kilómetros.</p>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<ul>
<li><p>Se puede ver que varios de los municipios alejados de la capital sufren cierto grado de pobreza o un alto NBI</p></li>
<li><p>Se puede ver que en el departamento del Cauca hay un porcentaje que no es bajo de NBI si miramos todos los municipios ya que la mayoria de estos superan el 20%.</p></li>
</ul>
</section>
<section id="recomendaciones" class="level1">
<h1>Recomendaciones</h1>
<ul>
<li>Hacer un estudio más riguroso sobre las posibles relaciones que existan entre estás variables para determinar si existe algún grado de correlación</li>
</ul>
</section>
<section id="cibergrafía" class="level1">
<h1>Cibergrafía</h1>
<p>OpenAI. (2025). ChatGPT [Modelo de lenguaje AI]. Recuperado de <a href="https://chat.openai.com" class="uri">https://chat.openai.com</a></p>
<p>Mejores Rutas. Calculadora de distancia de conducción en Cauca. Recuperado de <a href="https://colombia.mejoresrutas.com/tabla-de-distancias/co-cauca/" class="uri">https://colombia.mejoresrutas.com/tabla-de-distancias/co-cauca/</a></p>
<p>Necesidades Básicas Insatisfechas (NBI)(2018). Recuperado de <a href="https://www.dane.gov.co/index.php/estadisticas-por-tema/pobreza-y-condiciones-de-vida/necesidades-basicas-insatisfechas-nbi" class="uri">https://www.dane.gov.co/index.php/estadisticas-por-tema/pobreza-y-condiciones-de-vida/necesidades-basicas-insatisfechas-nbi</a></p>
<p>Kaggle. Colombia GeoJSON municipios. Recuperado de <a href="https://www.kaggle.com/datasets/alfredomaussa/colombia-geojson-municipios" class="uri">https://www.kaggle.com/datasets/alfredomaussa/colombia-geojson-municipios</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>