---
title: "Mapas del Departamento del Cauca"
author: 
  - "Juan Camilo Gutiérrez Martínez CC 1033486192"
  - "Maria Fernanda Calle Agudelo CC 1033428469"
  - "Jaider Castañeda Villa CC 1001015442"
date: last-modified
format: 
  html:
    toc: true
editor: visual
execute:
  echo: false
  warning: false
  message: false
---

# Introducción

# Objetivos

# Metodología y Procedimientos

# Mapas

## Mapa del departamento

```{r}
library(sf)
library(ggplot2)
library(dplyr)
library(stringi)              # Cada vez que lo uses

# Cargar archivo GeoJSON
geo_data <- st_read("municipios_GeoJSON.geojson", quiet = TRUE)

# Convertir columna dpt a texto
geo_data$dpt <- as.character(geo_data$dpt)

# Filtrar solo Cauca
geo_cauca <- geo_data %>% filter(dpt == "CAUCA")
geo_cauca <- geo_cauca %>% filter(!is.na(name))
geo_cauca$name <- stri_trans_general(geo_cauca$name, "Latin-ASCII")

municipios <- unique(geo_cauca$name)
colores_personalizados <- setNames(
  rainbow(length(municipios)),  # o cualquier otro vector de colores
  municipios
)

ggplot(geo_cauca) +
  geom_sf(aes(fill = name), color = "black", size = 0.2) +
  scale_fill_manual(values = colores_personalizados) +
  theme_minimal() +
  labs(title = "Municipios del Cauca con colores asignados manualmente")


```

## Distribución de la pobreza

```{r}
library(readxl)
library(dplyr)
library(viridis)  # opcional, para una paleta perceptualmente uniforme

nbi_data <- read_excel("CNPV-2018-NBI.xlsx", sheet = "Municipios")
nbi_data_cauca <- nbi_data %>% filter(`Nombre Departamento` == "CAUCA")

nbi_reducido <- nbi_data_cauca %>%
  select(`Nombre Municipio`, `Prop de Personas en NBI (%)...5`)

nbi_reducido$`Nombre Municipio` <- stri_trans_general(nbi_reducido$`Nombre Municipio`, "Latin-ASCII")

geo_json_with_nbi <- left_join(geo_cauca, nbi_reducido, by = c("name" = "Nombre Municipio"))


ggplot(geo_json_with_nbi) +
  geom_sf(aes(fill = `Prop de Personas en NBI (%)...5`), color = "black", size = 0.2) +
  scale_fill_gradientn(
    colours = c("green", "yellow", "orange", "red"),
    name = "NBI (%)"
  ) +
  theme_minimal() +
  labs(title = "Índice de Necesidades Básicas Insatisfechas (NBI) - Cauca")

```

## Índice del desempeño fiscal

```{r}
idf_data <- read_excel("ResultadosIDF_2023.xlsx", sheet = "Municipios 2023")
idf_data_cauca <- idf_data %>% filter(`Departamento` == "CAUCA")

idf_reducido <- idf_data_cauca %>%
  select(`Código`,`Municipio`, `Nuevo IDF`,`Rango`)

idf_reducido$`Municipio` <- stri_trans_general(idf_reducido$`Municipio`, "Latin-ASCII")

geo_json_with_idf <- left_join(geo_cauca, idf_reducido, by = c("id" = "Código"))

ggplot(geo_json_with_idf) +
  geom_sf(aes(fill = Rango), color = "black", size = 0.2) +
  scale_fill_manual(
    values = c(
      "1. Deterioro (<40)" = "red",
      "2. Riesgo (>=40 y <60)" = "orange",
      "3. Vulnerable (>=60 y <70)" = "yellow",
      "4. Solvente (>=70 y <80)" = "lightgreen",
      "5. Sostenible (>=80)" = "green" 
    ),
    name = "Clasificación Municipio"
  ) +
  theme_minimal() +
  labs(title = "Índice Desempeño Fiscal (IDF) 2023- Cauca")



```

## Distancia a la capital 

# Conclusiones

# Recomendaciones

# Cibergrafía
